"""Configuration file.

Set `WIFI_NETWORK` and `WIFI_NETWORK_PASSWORD` if `CONNECT_WIFI = True`
Set `WEB_REPL_PASSWORD` if  `WEB_REPL = True`
"""

LOGGING_LEVEL = "DEBUG"
FILE_LOGGING_LEVEL = "DEBUG"

CONNECT_WIFI = False
WIFI_NETWORK = ""
WIFI_NETWORK_PASSWORD = ""

WEB_REPL = False
WEB_REPL_PASSWORD = ""
